### ISSUE TITLE
README is displayed as webpage

### ISSUE THREAD

**Issue by christianholland** [Anupam-dagar/GitHub-Education-Portfolio#8]
Dear Anupam,

thank you very much for providing this tutorial on how to build a portfolio with Github Education packages, very useful!

I followed the manual but for some reasons the README file is displayed on the webpage (http://www.christianholland.me; corresponding repo: https://github.com/christianholland/christianholland.github.io). Locally (with `yarn start`) everything works perfectly fine.

I have the feeling it might be related to the DNS setting. Attached you find a screenshot of my current DNS records. During my tries to fix the issue I deleted the records that were listed by default. 

I would be very grateful if could help me to solve this issue.

Many thanks,
Christian

![image](https://user-images.githubusercontent.com/28303875/81289707-25e4bc00-9067-11ea-8a47-1535aa5c53c4.jpeg)

**Comment by kjaisingh** [comment]
I've got the same issue!

**Comment by christianholland** [comment]
Hi @kjaisingh,

I saw on your GitHub profile that you apparently managed to deploy the website correctly. Would you tell me how you solved this issue?

Best,
Christian

**Comment by kjaisingh** [comment]
Hi Christian! Rather than creating a repository in the format yourusername.github.io, use a custom repository name - this allows you to employ the gh-pages branch of the project, which should work! Let me know if you have any other questions.

**Comment by Anupam-dagar** [comment]
Hi @christianholland @kjaisingh. Can you confirm if your source is selected as `gh-pages` branch in the repo settings? Selecting `gh-pages` as your source branch should fix the issue. 
![image](https://user-images.githubusercontent.com/21174572/83481977-bc26c900-a4d1-11ea-9fef-6739dfa4469e.png)

**Comment by christianholland** [comment]
Dear @Anupam-dagar,

many thanks for reply. Based on your tutorial I named my repo in the format `username.github.io`. But apparently for this setting it is only possible to build the page from the master and not the gh-page branch (see screenshot below).

However, renaming the repo e.g. to `portfolio` (that was also suggested by @kjaisingh) allows to specify the gh-page branch. But then the page is said to be deployed at https://christianholland.github.io/portfolio/. However, also here its not working, showing just the README.

Interestingly when I select the master branch the page is build correctly at https://christianholland.me. After 1-2 minutes the page stops working and shows instead the README again.

very confusing

![image](https://user-images.githubusercontent.com/28303875/83502889-8af2cc80-a4c2-11ea-9567-4e84504700a7.jpeg)

**Comment by Anupam-dagar** [comment]
@christianholland No need to create a separate repo for it.
To publish on your `githubusername.github.io` please replace the deploy command in package.json with the following one.
```diff
- deploy: gh-pages -d build
+ deploy: gh-pages -d public -b master
```

This pushes your code to master and you can successfully access your website and not the readme. To save your code, you can create a separate branch and push that branch to keep your code..

**Comment by christianholland** [comment]
After inserting the deploy changes and running `yarn run deploy` I get the following error:

```
 gh-pages -d public -b master
fatal: A branch named 'master' already exists.
```

Does this mean I have to delete my current origin/master branch to push a new one?

**Comment by Anupam-dagar** [comment]
Deleting master and pushing again should be the last resort. I found that this is a common issue for `gh-pages` library. Can you try following the steps mentioned in here https://github.com/tschaub/gh-pages#tips and then deploying again.

**Comment by christianholland** [comment]
Thanks that helps...at least I can execute the command `yarn run deploy`. However,
as you can see [here](https://github.com/christianholland/christianholland.github.io/tree/master) there is basically now just a skeleton and no custom files. I made a backup [branch](https://github.com/christianholland/christianholland.github.io/tree/backup) with the old code. Should I now integrate the code from the backup branch into the new master?

Please apologise for all my questions. Your support is highly appreciated

**Comment by Anupam-dagar** [comment]
My bad @christianholland. I specified the wrong directory in my command provided. Please change your earlier deploy command to follows:
```diff
- gh-pages -d public -b master
+ gh-pages -d build -b master
```

`-d` flag specifies the destination folder which will be pushed. In earlier command, we specified public instead of build due to which you only saw the skeleton. Also just to ensure everything is fine, can you confirm if your `scripts` section in `package.json` is similar to the following:
```json
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "predeploy": "yarn run build",
    "deploy": "gh-pages -d build -b master"
  },
```
